repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.13.0
    hooks:
    -   id: reorder-python-imports
        args: [
            --application-directories, '.:src',
            --py38-plus,
            --add-import, 'from __future__ import annotations',
        ]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
    -   id: mypy
        exclude: ^(docs/|example-plugin/)

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.4'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
